# Generated by Django 3.0.8 on 2020-07-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('form_type', models.CharField(choices=[('40', '40%'), ('60', '60%'), ('65', '65%'), ('75', '75% (TKL)'), ('10', '100% (Full size)'), ('OR', 'Ortholinear'), ('ER', 'Ergonomic')], default='40', max_length=2)),
                ('material', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(choices=[('ABS', 'ABS'), ('PBT', 'PBT'), ('POM', 'POM')], default='ABS', max_length=3)),
                ('profile', models.CharField(choices=[('DS', 'DSA profile'), ('SA', 'SA profile'), ('OE', 'OEM profile'), ('KT', 'KAT profile'), ('CH', 'Cherry profile')], default='DS', max_length=2)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pcb_type', models.CharField(choices=[('SL', 'Solder'), ('HS', 'Hotswap')], default='SL', max_length=2)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stabilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stab_type', models.CharField(choices=[('S', 'Screw-in Stabilizers'), ('P', 'PCB-Mounted')], default='S', max_length=1)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('switch_type', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Case')),
                ('keycap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Keycap')),
                ('pcb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.PCB')),
                ('stabilizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Stabilizer')),
                ('switch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Switch')),
            ],
        ),
    ]
