# Generated by Django 3.0.8 on 2020-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='form_type',
            field=models.CharField(choices=[('40', '40%'), ('60', '60%'), ('65', '65%'), ('75', '75% (TKL)'), ('10', '100% (Full size)'), ('OR', 'Ortholinear'), ('ER', 'Ergonomic'), ('DE', 'Default')], default='40', max_length=2),
        ),
        migrations.AlterField(
            model_name='keycap',
            name='image',
            field=models.CharField(default='https://assets3.razerzone.com/xpQLMA117pPRYZvkU17ddE-vLLk=/767x511/https%3A%2F%2Fhybrismediaprod.blob.core.windows.net%2Fsys-master-phoenix-images-container%2Fhe1%2Fh98%2F9011301384222%2Frazer-pbt-keycap-upgrade-set-mercury-white-gallery-hero-1500x1000.jpg', max_length=1000),
        ),
    ]
